#import mini_projects.mortgage
#import practices.strings
#import mini_projects.triangle
#import mini_projects.pyramid
#import mini_projects.calculator
#import mini_projects.register
#import mini_projects.shape
#import practices.mammal
#import practices.listsPractice
#import mini_projects.store
#import practices.arguments
#import practices.lambdaPractice
#import practices.MFR
#import practices.recursion
#import practices.decorators
#import practices.docstringsPractice
#import practices.exceptions
#import practices.withPractice
#import practices.listComprehension
#import operatorOverloading